kind: Pod
apiVersion: v1
metadata:
  name: annotation
  annotation: 
    buildURL: "https://jenkins.com/expense/job/backend/23"
    imageregistry: "https://hub.docker.com"
spec:
 container:
  name: nginx
  image: nginx    